### PR TITLE
Use https

### PR DESCRIPTION
**Pull request by 1-alex98**

### CODE REVIEW

**Comment by Brutus5000** [comment]
https on localhost will never work, because let's encrypt needs to access the domain you claim to fetch a certificate for.

**Comment by 1-alex98** [comment]
ok true i was a little concerned about that as well

**Comment by 1-alex98** [comment]
So it is just a setting thing for production right

**Comment by 1-alex98** [comment]
You need to overwrite it with https on prod server

**Comment by Brutus5000** [comment]
Yes :)

**Pull request closed without merging**
