### PR TITLE
Remove faf-python-api (fixes #45)

### LINKED ISSUE #45: Remove python-api service
The java-api has superseded the python api for over a year now.
With the removal of [Jeremy](https://github.com/FAForever/faf-stack/issues/42) no service should depend on it anymore.

Should any service or client still rely on this, it needs to be moved to the java-api.

(This would also resolve #22)

### PR DESCRIPTION
**Pull request by Brutus5000**
The python api is stopped on production for a week now with no complaints so far.

### CODE REVIEW

**Comment by micheljung** [comment]
Still needed by the python server

**Comment by Rackover** [comment]
I don't think the python server needs it anymore

**Comment by micheljung** [comment]
It does, to update events and achievements. It does not support the Java API yet.

**Comment by Rackover** [comment]
Fixed.

**Pull request merged**
