### PR TITLE
Add tutorial env variable

### PR DESCRIPTION
**Pull request by 1-alex98**

### CODE REVIEW

**Comment by axel1200** [comment]
And update faf-voting-app

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
The example files all need to be runnable from localhost. And all links point to the localhost website.
So point it to localhost:\<port of content server> instead of faforever.com

**Comment by 1-alex98** [comment]
Ok

**Comment by Brutus5000** [comment]
@axel1200 Friendly reminder.

**Review by Brutus5000 — APPROVED** [review]

**Pull request merged**
